# directory for debug binary
DEBUGDIR := Debug

# directory for release binary
RELEASEDIR := Release

# output binary
BIN := NetMonitor

# base directory for sources
SRCDIRS := src

# include files
INC_DIRS := $(shell find $(SRCDIRS) -type d)
INC_FLAGS := $(addprefix -I,$(INC_DIRS))
# source files
SRCS := $(shell find $(SRCDIRS) -name "*.c" -o -name "*.cpp" -o -name "*.cc" -o -name "*.cxx")
SRCS_NAMES := $(notdir $(SRCS))

# files included in the tarball generated by 'make dist' (e.g. add LICENSE file)
DISTFILES := $(RELEASEDIR)/$(BIN) LICENSE README.md 

# filename of the tar archive generated by 'make dist'
DISTOUTPUT := $(BIN).tgz

# intermediate directory for generated object files
RELEASE_OBJDIR := $(RELEASEDIR)/obj
DEBUG_OBJDIR := $(DEBUGDIR)/obj
# intermediate directory for generated dependency files
DEPDIR := .deps

# object files, auto generated from source files
RELEASE_OBJS := $(subst $(SRCDIRS)/,,$(patsubst %,$(RELEASE_OBJDIR)/%.o,$(basename $(SRCS))))
DEBUG_OBJS := $(subst $(SRCDIRS)/,,$(patsubst %,$(DEBUG_OBJDIR)/%.o,$(basename $(SRCS))))

# dependency files, auto generated from source files
DEPS := $(subst $(SRCDIRS)/,,$(patsubst %,$(DEPDIR)/%.d,$(basename $(SRCS))))

# compilers (at least gcc and clang) don't create the subdirectories automatically
$(shell mkdir -p $(dir $(DEPS)) >/dev/null)

# C compiler
CC := gcc
# C++ compiler
CXX := g++
# linker
LD := gcc
# tar
TAR := tar

# C flags
CFLAGS := -pthread
CFLAGS_DEBUG := -ggdb -pthread
# C++ flags
CXXFLAGS := -pthread
CXXFLAGS_DEBUG := -ggdb -pthread
# C/C++ flags
CPPFLAGS := $(INC_FLAGS) -Wall -Wextra -pedantic
CPPFLAGS_DEBUG := $(INC_FLAGS) -Wall -Wextra -pedantic -DDEBUG=2
# linker flags
LDFLAGS :=
LDFLAGS_DEBUG := -ggdb
# linker libraries
LDLIBS := -lcurses -lpcap -lpthread -lip4tc -lnetfilter_conntrack
# flags required for dependency generation; passed to compilers
DEPFLAGS = -MT $@ -MD -MP -MF $(DEPDIR)/$*.Td

# compile C source files
COMPILE.c = $(CC) $(DEPFLAGS) $(CFLAGS) $(CPPFLAGS) -c -o $@
COMPILE_DEBUG.c = $(CC) $(DEPFLAGS) $(CFLAGS_DEBUG) $(CPPFLAGS_DEBUG) -c -o $@
# compile C++ source files
COMPILE.cc = $(CXX) $(DEPFLAGS) $(CXXFLAGS) $(CPPFLAGS) -c -o $@
COMPILE_DEBUG.cc = $(CXX) $(DEPFLAGS) $(CXXFLAGS_DEBUG) $(CPPFLAGS_DEBUG) -c -o $@
# precompile step
PRECOMPILE =
# postcompile step
POSTCOMPILE = mv -f $(DEPDIR)/$*.Td $(DEPDIR)/$*.d

all: release debug

release: $(RELEASEDIR) $(RELEASEDIR)/$(BIN)
	$(shell strip --strip-debug $^)
	$(shell strip --strip-debug $(RELEASE_OBJS))

debug: $(DEBUGDIR) $(DEBUGDIR)/$(BIN)

$(RELEASEDIR):
	$(shell mkdir -p $(RELEASEDIR) >/dev/null)

$(DEBUGDIR):
	$(shell mkdir -p $(DEBUGDIR) >/dev/null)

dist: $(DISTFILES)
	$(TAR) -cvzf $(DISTOUTPUT) $^

.PHONY: clean
clean:
	$(RM) -r $(DEPDIR) $(RELEASEDIR) $(DEBUGDIR)

.PHONY: distclean
distclean: clean
	$(RM) $(DISTOUTPUT)

.PHONY: install
install:
	@echo no install tasks configured

.PHONY: uninstall
uninstall:
	@echo no uninstall tasks configured

.PHONY: check
check:
	@echo no tests configured

.PHONY: list
list:
	@echo $(SRCS)
	@echo $(INC_DIRS)
	@echo $(DEPS)
	@echo $(RELEASE_OBJS)
	@echo $(DEBUG_OBJS)
	@echo $(BIN)
	
.PHONY: help
help:
	@echo available targets: all release debug dist clean distclean install uninstall check

# Rule to make release executable
$(RELEASEDIR)/$(BIN): $(RELEASE_OBJDIR) $(RELEASE_OBJS)
	$(LD) -o $@ $(RELEASE_OBJS) $(LDFLAGS) $(LDLIBS) 
	
# Rule to make debugging executable (with debugging symbols) 
$(DEBUGDIR)/$(BIN): $(DEBUG_OBJDIR) $(DEBUG_OBJS)
	$(LD) -o $@ $(DEBUG_OBJS) $(LDFLAGS_DEBUG) $(LDLIBS) 

$(RELEASE_OBJDIR):
	$(shell mkdir -p $(RELEASE_OBJDIR) >/dev/null)

$(DEBUG_OBJDIR):
	$(shell mkdir -p $(DEBUG_OBJDIR) >/dev/null)

# Rules to make release objs
$(RELEASE_OBJDIR)/%.o: $(SRCDIRS)/%.c
$(RELEASE_OBJDIR)/%.o: $(SRCDIRS)/%.c $(DEPDIR)/%.d
	$(PRECOMPILE)
	$(COMPILE.c) $<
	$(POSTCOMPILE)

$(RELEASE_OBJDIR)/%.o: $(SRCDIRS)/%.cpp
$(RELEASE_OBJDIR)/%.o: $(SRCDIRS)/%.cpp $(DEPDIR)/%.d
	$(PRECOMPILE)
	$(COMPILE.cc) $<
	$(POSTCOMPILE)

$(RELEASE_OBJDIR)/%.o: $(SRCDIRS)/%.cc
$(RELEASE_OBJDIR)/%.o: $(SRCDIRS)/%.cc $(DEPDIR)/%.d
	$(PRECOMPILE)
	$(COMPILE.cc) $<
	$(POSTCOMPILE)

$(RELEASE_OBJDIR)/%.o: $(SRCDIRS)/%.cxx
$(RELEASE_OBJDIR)/%.o: $(SRCDIRS)/%.cxx $(DEPDIR)/%.d
	$(PRECOMPILE)
	$(COMPILE.cc) $<
	$(POSTCOMPILE)

# Rule to make debugging objs (with debugging symbols) 
$(DEBUG_OBJDIR)/%.o: $(SRCDIRS)/%.c
$(DEBUG_OBJDIR)/%.o: $(SRCDIRS)/%.c $(DEPDIR)/%.d
	$(PRECOMPILE)
	$(COMPILE_DEBUG.c) $<
	$(POSTCOMPILE)

$(DEBUG_OBJDIR)/%.o: $(SRCDIRS)/%.cpp
$(DEBUG_OBJDIR)/%.o: $(SRCDIRS)/%.cpp $(DEPDIR)/%.d
	$(PRECOMPILE)
	$(COMPILE_DEBUG.cc) $<
	$(POSTCOMPILE)

$(DEBUG_OBJDIR)/%.o: $(SRCDIRS)/%.cc
$(DEBUG_OBJDIR)/%.o: $(SRCDIRS)/%.cc $(DEPDIR)/%.d
	$(PRECOMPILE)
	$(COMPILE_DEBUG.cc) $<
	$(POSTCOMPILE)

$(DEBUG_OBJDIR)/%.o: $(SRCDIRS)/%.cxx
$(DEBUG_OBJDIR)/%.o: $(SRCDIRS)/%.cxx $(DEPDIR)/%.d
	$(PRECOMPILE)
	$(COMPILE_DEBUG.cc) $<
	$(POSTCOMPILE)

.PRECIOUS: $(DEPDIR)/%.d
$(DEPDIR)/%.d: ;

-include $(DEPS)